# Generated by Django 5.0.6 on 2024-06-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='dni',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
