# Generated by Django 5.0.6 on 2024-08-06 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Agenda', '0001_initial'),
        ('basic', '0001_initial'),
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('horaInicio', models.TimeField()),
                ('horaFin', models.TimeField()),
                ('observaciones', models.TextField()),
                ('esSobreturno', models.BooleanField()),
                ('monto', models.FloatField()),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Asignado', 'Asignado'), ('Cancelado', 'Cancelado'), ('Realizado', 'Realizado')], default='Disponible', max_length=20)),
                ('administrativo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('agenda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Agenda.agenda')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='TurnosPieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pieza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.piezadental')),
                ('prestacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.prestacion')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnos.turno')),
            ],
        ),
    ]
