# Generated by Django 5.0.6 on 2024-08-19 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_alter_turno_options_alter_turno_administrativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='monto',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
