# Generated by Django 5.0.7 on 2024-08-03 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('agendaID', models.AutoField(primary_key=True, serialize=False)),
                ('CentroOdontologicoID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic.centroodontologico')),
                ('odontologoID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic.odontologo')),
            ],
        ),
        migrations.CreateModel(
            name='turnoTemplate',
            fields=[
                ('turnoTemplateId', models.AutoField(primary_key=True, serialize=False)),
                ('horaInicio', models.TimeField()),
                ('horaFin', models.TimeField()),
                ('diaSemana', models.CharField(max_length=20)),
                ('agendaID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos', to='Agenda.agenda')),
            ],
        ),
    ]
