# Generated by Django 5.0.7 on 2024-08-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='agendaID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='turnotemplate',
            name='turnoTemplateId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
