# Generated by Django 5.0.6 on 2024-08-14 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0002_rename_agendaid_agenda_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnotemplate',
            name='diaSemana',
            field=models.PositiveSmallIntegerField(choices=[(0, 'LUNES'), (1, 'MARTES'), (2, 'MIERCOLES'), (3, 'JUEVES'), (4, 'VIERNES'), (5, 'SABADO'), (6, 'DOMINGO')]),
        ),
    ]
