# Generated by Django 5.0.6 on 2024-11-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0003_alter_turnotemplate_diasemana'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='nombre',
            field=models.CharField(default='sin nombre', max_length=100),
            preserve_default=False,
        ),
    ]
