# Generated by Django 5.0.6 on 2024-07-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestacion',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
    ]
