# Generated by Django 5.0.6 on 2024-11-25 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_prestacion_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odontologo',
            name='matricula',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
