# Generated by Django 5.0.6 on 2024-11-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_alter_odontologo_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='odontologo',
            name='identificador',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
