# Generated by Django 5.0.6 on 2024-11-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_odontologo_identificador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odontologo',
            name='identificador',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='odontologo',
            name='matricula',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
