# Generated by Django 5.0.6 on 2024-11-25 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_alter_odontologo_identificador_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='odontologo',
            old_name='identificador',
            new_name='id',
        ),
    ]
