# Generated by Django 5.0.6 on 2024-11-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0006_rename_identificador_odontologo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odontologo',
            name='matricula',
            field=models.CharField(max_length=30),
        ),
    ]
